# Netlify configuration file for Hugo

[build]
  base = ""  # Root of your repository
  publish = "public"  # Hugo outputs the site here
  command = "npm run project-setup && hugo build"  # Build command

[build.environment]
  HUGO_VERSION = "0.160.2"  # Use the latest Hugo version
